import{i as g,s as v}from"./assets/vendor-39182df4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function d(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=d(e);fetch(e.href,t)}})();const h="live_qfpFZuQ1otKVFKxl4WKh5WQKamlGxuK4LMaKO1lHDDzVK00ThJZEjFtnx98ZGrG5",u="https://api.thecatapi.com/v1",S=()=>fetch(`${u}/breeds`,{headers:{"x-api-key":h}}).then(c=>c.json()),b=c=>fetch(`${u}/images/search?breed_ids=${c}`,{headers:{"x-api-key":h}}).then(r=>r.json()).then(r=>r[0]);document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".select-wrapper"),r=()=>c.classList.remove("hide"),d=()=>c.classList.add("hide"),a=document.querySelector(".loader-wrapper"),e=()=>a.classList.remove("hide"),t=()=>a.classList.add("hide"),n=document.querySelector(".cat-info"),p=()=>n.classList.remove("hide"),f=()=>n.classList.add("hide"),l=()=>g.error({title:"Error",message:"An error occurred. Please try again later.",position:"topRight"}),m=s=>{const o=s.map(i=>({text:i.name,value:i.id}));new v({select:"#breed-select",placeholder:"Select a breed",searchPlaceholder:"Search a breed",data:o,events:{afterChange:i=>y(i[0].value)}}),r()},y=s=>{s&&(f(),e(),d(),b(s).then(o=>{t(),r(),L(o)}).catch(()=>{t(),l()}))},L=s=>{const o=s.breeds[0];n.innerHTML=`
      <img src="${s.url}" alt="${o.name}" />
      <div class="details">
        <h2 class="title">${o.name}</h2>
        <p class="description">${o.description}</p>
        <p><strong>Temperament:</strong> ${o.temperament}</p>
      </div>
    `,p()};e(),S().then(s=>{m(s),t()}).catch(()=>{t(),l()})});
//# sourceMappingURL=commonHelpers.js.map
